version: "3.7"
services:
  node:
    build: .docker/angular-cli
    image: angular-cli
    container_name: node-investigar
    user: node
    working_dir: /home/node/app 
    ports:
      - "4200:4200"
    volumes:
      - .:/home/node/app
    command: ng serve --host 0.0.0.0 --disable-host-check
  web:
    build: .docker/nginx
    image: nginx-investigar
    container_name: web-investigar
    ports:
      - "4280:80"
    volumes:
      - ./dist/appweb:/usr/share/nginx/html



