export const VERSION_NUMBER: string = "01-072022";

// ENCODE ADMIN CONSTANTS

export const CSV_SEPARATOR = "_";
export const PAGE_SIZE = 5;

export const encodeCSVFields = [
    "uid",
    "name",
    "email",
    "creationDate",
    "abandonedByUser",
    "consent_hasAccepted",
    "consent_date",
    "personalInfo_age",
    "personalInfo_educationLevel",
    "personalInfo_gender",
    "personalInfo_occupation",
    "personalInfo_ongoingCareer",
    "healthInfo_cronicMedicines",
    "healthInfo_hasSleepDisorder",
    "healthInfo_sleepDisorders",
    "healthInfo_takesCronicMedicine",
    "sessionOne_completed",
    "sessionOne_somnolenceDegree",
    "sessionTwo_completed",
    "sessionTwo_somnolenceDegree",
    "sessionTwo_perpetratorCondition",
    "googleFormsResponses_0_isResponded",
    "googleFormsResponses_1_isResponded",
    "googleFormsResponses_2_isResponded",
    "googleFormsResponses_3_isResponded",
    "googleFormsResponses_4_isResponded",
    "googleFormsResponses_5_isResponded",
    "sessionTwo_identificationResponse_0_confidenceLevel",
    "sessionTwo_identificationResponse_0_selectedSuspect_id",
    "sessionTwo_identificationResponse_0_selectedSuspect_isPerpetrator",
    "sessionTwo_identificationResponse_1_confidenceLevel",
    "sessionTwo_identificationResponse_1_selectedSuspect_id",
    "sessionTwo_identificationResponse_1_selectedSuspect_isPerpetrator",
    "sessionTwo_imageSelectionResponse_0_id",
    "sessionTwo_imageSelectionResponse_1_id",
    "sessionTwo_imageSelectionResponse_2_id",
    "sessionTwo_imageSelectionResponse_3_id",
    "sessionTwo_imageSelectionResponse_4_id",
    "sessionTwo_imageSelectionResponse_5_id",
    "sessionTwo_imageSelectionResponse_6_id",
    "sessionTwo_imageSelectionResponse_7_id",
    "sessionTwo_imageSortingResponse_0_id",
    "sessionTwo_imageSortingResponse_1_id",
    "sessionTwo_imageSortingResponse_2_id",
    "sessionTwo_imageSortingResponse_3_id",
    "sessionTwo_imageSortingResponse_4_id",
    "sessionTwo_imageSortingResponse_5_id",
    "sessionTwo_imageSortingResponse_6_id",
    "sessionTwo_imageSortingResponse_7_id",
    "link_audios"
  ];
